#!/bin/sh

logger -t $(basename $0) "started [$@]"

# Moving web interface to another port.
# You'll need it while using your own web-server on 80 port
/usr/bin/killall httpd
cd /www
/usr/sbin/httpd -p 60080 &

# /opt is a symlink to /tmp/opt in AsusWRT. If you are using Entware/Optware do
ln -sf /tmp/mnt/ENTWARE /tmp/opt

# Wait up to 15 seconds to make sure Entware partition is mounted
i=0
while [ $i -le 15 ]
do
    if [ -d /opt/etc ]
    then
	break
    fi
    sleep 1
    i=`expr $i + 1`
done

# Starting Entware services
/opt/etc/init.d/rc.unslung start
